from typing import Any

class WriteBackResult:
    edited_files: dict[str, str]
    changed_files: list[str]
    changed_declarations: list[str]
    mode: str
    validation_ok: bool
    validation_message: str | None

class ModelBuilder:
    def __init__(self, validate_each_mutation: bool = True) -> None: ...
    def add_package(self, target_file: str, name: str) -> WriteBackResult: ...
    def add_definition(
        self,
        container: str,
        keyword: str,
        name: str,
        specializes: list[str] | None = None,
    ) -> WriteBackResult: ...
    def add_usage(
        self,
        container: str,
        keyword: str,
        name: str,
        ty: str | None = None,
        specializes: list[str] | None = None,
    ) -> WriteBackResult: ...
    def set_expression(self, element: str, expression: str | None = None) -> WriteBackResult: ...
    def set_attribute(self, element: str, attribute: str, value: Any) -> WriteBackResult: ...
    def rendered_files(self) -> dict[str, str]: ...
    def compile_model(self) -> Any: ...

class PyWorkspace:
    @staticmethod
    def open(path: str) -> PyWorkspace: ...
    def model(self) -> Any: ...
    def parts(self) -> list[Any]: ...
    def element(self, id: str) -> Any | None: ...
    def compile(self) -> Any: ...
    def list_analysis_cases(self) -> list[str]: ...
    def run_analysis(self, case_id: str) -> Any: ...
