from typing import Any, NoReturn

class WriteBackResult:
    edited_files: dict[str, str]
    changed_files: list[str]
    changed_declarations: list[str]
    mode: str
    validation_ok: bool
    validation_message: str | None

class ModelBuilder:
    def __init__(self, validate_each_mutation: bool = True) -> None: ...
    @classmethod
    def from_project(
        cls,
        path: str,
        validate_each_mutation: bool = True,
    ) -> ModelBuilder: ...
    @classmethod
    def from_sysml_files(
        cls,
        files: dict[str, str],
        validate_each_mutation: bool = True,
    ) -> ModelBuilder: ...
    def add_package(self, target_file: str, name: str) -> WriteBackResult: ...
    def add_import(
        self,
        target_file: str,
        path: str,
        package_name: str | None = None,
    ) -> WriteBackResult: ...
    def remove_import(
        self,
        target_file: str,
        path: str,
        package_name: str | None = None,
    ) -> WriteBackResult: ...
    def add_definition(
        self,
        container: str,
        keyword: str,
        name: str,
        specializes: list[str] | None = None,
    ) -> WriteBackResult: ...
    def remove_declaration(self, element: str) -> WriteBackResult: ...
    def update_specializations(
        self,
        element: str,
        specializes: list[str],
    ) -> WriteBackResult: ...
    def add_relationship(
        self,
        container: str,
        kind: str,
        source: str,
        target: str,
    ) -> WriteBackResult: ...
    def add_metadata_annotation(
        self,
        element: str,
        metadata_type: str,
        properties: dict[str, str] | None = None,
    ) -> WriteBackResult: ...
    def add_usage(
        self,
        container: str,
        keyword: str,
        name: str,
        ty: str | None = None,
        specializes: list[str] | None = None,
    ) -> WriteBackResult: ...
    def set_expression(self, element: str, expression: str | None = None) -> WriteBackResult: ...
    def set_usage_type(self, element: str, ty: str | None = None) -> WriteBackResult: ...
    def set_attribute(self, element: str, attribute: str, value: Any) -> WriteBackResult: ...
    def add_attribute_value(self, element: str, attribute: str, value: Any) -> WriteBackResult: ...
    def remove_attribute_value(self, element: str, attribute: str, value: Any) -> WriteBackResult: ...
    def clear_attribute(self, element: str, attribute: str) -> WriteBackResult: ...
    def move_declaration(self, element: str, destination: str) -> WriteBackResult: ...
    def render_file(self, path: str) -> str: ...
    def files(self) -> list[str]: ...
    def rendered_files(self) -> dict[str, str]: ...
    def compile_json(self) -> str: ...
    def compile_model(self) -> SemanticModel: ...
    def validate(self) -> WriteBackResult: ...

class ElementView:
    id: str
    kind: str
    layer: int
    def metatype_id(self) -> str | None: ...
    def get_json(self, name: str) -> str | None: ...
    def effective_json(self, name: str) -> str | None: ...
    def get_str(self, name: str) -> str | None: ...
    def effective_str(self, name: str) -> str | None: ...
    def references(self, relation: str) -> list[ElementView]: ...
    def attribute_names(self) -> list[str]: ...

class SemanticModel:
    @classmethod
    def from_kir_json(cls, content: str) -> SemanticModel: ...
    def element(self, element_id: str) -> ElementView: ...
    def elements(self) -> list[ElementView]: ...
    def element_count(self) -> int: ...
    def semantic_snapshot_json(self) -> str: ...
    def generate_python_wrappers(self, module_name: str) -> dict[str, str]: ...
    def model_metadata_json(self) -> str: ...
    def graph_view_json(self, scope: str | None = None) -> str: ...
    def search_json(self, query: str) -> str: ...
    def element_details_json(self, element_id: str) -> str: ...
    def l2_explorer_json(self, request_json: str) -> str: ...
    def metatype_explorer_json(self, request_json: str) -> str: ...
    def library_tree_json(self) -> str: ...
    def dsl_query_json(self, source: str) -> str: ...
    def dsl_schema_json(self) -> str: ...
    def run_cell_json(self, request_json: str) -> str: ...
    def preview_transaction_json(self, request_json: str) -> str: ...

class PyPartRef:
    id: str
    name: str
    kind: str
    element_kind: str
    parent_id: str | None
    depth: int
    def attr(self, name: str) -> str | None: ...
    def json(self) -> str: ...

class PyKirElement:
    id: str
    label: str
    kind: str
    layer: int
    def json(self) -> str: ...

class PyWorkspace:
    @staticmethod
    def open(path: str) -> PyWorkspace: ...
    def model(self) -> str: ...
    def graph(self) -> str: ...
    def parts(self) -> list[PyPartRef]: ...
    def element(self, id: str) -> PyKirElement | None: ...
    def compile(self) -> SemanticModel: ...
    def model_metadata_json(self) -> str: ...
    def graph_view_json(self, scope: str | None = None) -> str: ...
    def search_json(self, query: str) -> str: ...
    def element_details_json(self, element_id: str) -> str: ...
    def l2_explorer_json(self, request_json: str) -> str: ...
    def metatype_explorer_json(self, request_json: str) -> str: ...
    def library_tree_json(self) -> str: ...
    def dsl_query_json(self, source: str) -> str: ...
    def dsl_schema_json(self) -> str: ...
    def run_cell_json(self, request_json: str) -> str: ...
    def list_analysis_cases(self) -> NoReturn: ...
    def run_analysis(self, case_id: str) -> NoReturn: ...
