from pathlib import Path
from typing import Any

class ModelBuilder:
    def __init__(self) -> None: ...
    @classmethod
    def for_metamodel(cls, id: str) -> ModelBuilder: ...
    def in_package(self, name: str) -> ModelBuilder: ...
    def add(self, element: _Declaration) -> ModelBuilder: ...
    def to_sysml(self) -> dict[str, str]: ...
    def compile(self) -> Any: ...
    def save(self, path: str | Path) -> None: ...

class _Declaration:
    def __init__(self, name: str) -> None: ...
    def specializes(self, target: Any): ...
    def typed(self, target: Any): ...
    def expression(self, text: str): ...
    def multiplicity(self, text: str): ...
    def direction(self, text: str): ...
    def doc(self, text: str): ...
    def abstract_(self): ...

class _Definition(_Declaration):
    def with_part(self, member: _Declaration): ...
    def with_item(self, member: _Declaration): ...
    def with_attr(self, member: _Declaration): ...
    def with_port(self, member: _Declaration): ...
    def with_end(self, member: _Declaration): ...
    def with_action(self, member: _Declaration): ...
    def with_state(self, member: _Declaration): ...

class _Usage(_Declaration): ...
class PartDefinition(_Definition): ...
class PartUsage(_Usage): ...
class ItemDefinition(_Definition): ...
class ItemUsage(_Usage): ...
class AttributeDefinition(_Definition): ...
class AttributeUsage(_Usage): ...
class PortDefinition(_Definition): ...
class PortUsage(_Usage): ...
class ConnectionDefinition(_Definition): ...
class ConnectionUsage(_Usage): ...
class ActionDefinition(_Definition): ...
class StateDefinition(_Definition): ...
class RequirementDefinition(_Definition): ...
class InterfaceDefinition(_Definition): ...
