from pathlib import Path
from typing import Any

class ModelBuilder:
    def __init__(self) -> None: ...
    @classmethod
    def for_metamodel(cls, id: str) -> ModelBuilder: ...
    @classmethod
    def from_project(
        cls,
        path: str | Path,
        *,
        validate: bool = True,
    ) -> ModelBuilder: ...
    @classmethod
    def from_files(
        cls,
        files: dict[str, str],
        *,
        validate: bool = True,
    ) -> ModelBuilder: ...
    def in_package(self, name: str, *, stdlib_imports: bool = True) -> ModelBuilder: ...
    def add(self, element: _Declaration) -> ModelBuilder: ...
    def add_to(self, container: str, element: _Declaration) -> ModelBuilder: ...
    def create(
        self,
        metaclass: str,
        name: str,
        *,
        container: str | None = None,
        type: Any = None,
        ty: Any = None,
        specializes: Any = None,
        additional_types: Any = None,
        subsets: Any = None,
        redefines: Any = None,
        reference_target: Any = None,
        transition_source: Any = None,
        transition_target: Any = None,
        trigger: str | None = None,
        doc: str | None = None,
        body: str | None = None,
        expression: str | None = None,
        multiplicity: str | None = None,
        direction: str | None = None,
        short_name: str | None = None,
        annotated_elements: Any = None,
        language_extensions: Any = None,
        language_extension_keyword: bool | None = None,
        abstract: bool | None = None,
        end: bool | None = None,
        individual: bool | None = None,
        attributes: dict[str, Any] | None = None,
    ) -> str: ...
    def rename(self, qualified_name: str, new_name: str) -> ModelBuilder: ...
    def remove(self, qualified_name: str) -> ModelBuilder: ...
    def add_import(
        self,
        path: Any,
        *,
        package: str | None = None,
        target_file: str | None = None,
    ) -> ModelBuilder: ...
    def remove_import(
        self,
        path: Any,
        *,
        package: str | None = None,
        target_file: str | None = None,
    ) -> ModelBuilder: ...
    def update_specializations(self, qualified_name: str, specializes: Any) -> ModelBuilder: ...
    def add_specialization(self, qualified_name: str, target: Any) -> ModelBuilder: ...
    def remove_specialization(self, qualified_name: str, target: Any) -> ModelBuilder: ...
    def set_type(self, qualified_name: str, target: Any | None) -> ModelBuilder: ...
    def set_expression(
        self,
        qualified_name: str,
        expression: str | None,
    ) -> ModelBuilder: ...
    def set_doc(self, qualified_name: str, text: str) -> ModelBuilder: ...
    def clear_doc(self, qualified_name: str) -> ModelBuilder: ...
    def set_attribute(self, qualified_name: str, attribute: str, value: Any) -> ModelBuilder: ...
    def clear_attribute(self, qualified_name: str, attribute: str) -> ModelBuilder: ...
    def add_attribute_value(self, qualified_name: str, attribute: str, value: Any) -> ModelBuilder: ...
    def remove_attribute_value(self, qualified_name: str, attribute: str, value: Any) -> ModelBuilder: ...
    def move(self, qualified_name: str, destination: str) -> ModelBuilder: ...
    def add_relationship(
        self,
        kind: str,
        source: Any,
        target: Any,
        *,
        container: str | None = None,
    ) -> ModelBuilder: ...
    def add_metadata(
        self,
        qualified_name: str,
        metadata_type: str,
        properties: dict[str, str] | None = None,
    ) -> ModelBuilder: ...
    def set_additional_types(self, qualified_name: str, values: Any) -> ModelBuilder: ...
    def add_additional_type(self, qualified_name: str, value: Any) -> ModelBuilder: ...
    def remove_additional_type(self, qualified_name: str, value: Any) -> ModelBuilder: ...
    def set_subsets(self, qualified_name: str, values: Any) -> ModelBuilder: ...
    def add_subset(self, qualified_name: str, value: Any) -> ModelBuilder: ...
    def remove_subset(self, qualified_name: str, value: Any) -> ModelBuilder: ...
    def set_redefines(self, qualified_name: str, values: Any) -> ModelBuilder: ...
    def add_redefine(self, qualified_name: str, value: Any) -> ModelBuilder: ...
    def remove_redefine(self, qualified_name: str, value: Any) -> ModelBuilder: ...
    def set_reference_target(self, qualified_name: str, target: Any) -> ModelBuilder: ...
    def clear_reference_target(self, qualified_name: str) -> ModelBuilder: ...
    def to_sysml(self) -> dict[str, str]: ...
    def compile(self) -> Any: ...
    def save(self, path: str | Path | None = None) -> None: ...

class _Declaration:
    def __init__(self, name: str) -> None: ...
    def specializes(self, target: Any): ...
    def typed(self, target: Any): ...
    def expression(self, text: str): ...
    def multiplicity(self, text: str): ...
    def direction(self, text: str): ...
    def doc(self, text: str): ...
    def abstract_(self): ...
    def reference_target(self, target: Any): ...
    def language_extension(self, keyword: str): ...
    def extension_keyword(self): ...
    def first(self, source: Any): ...
    def initial(self, source: Any = "start"): ...
    def then(self, target: Any): ...
    def accept(self, trigger: str): ...

class _Definition(_Declaration):
    def with_part(self, member: _Declaration): ...
    def with_item(self, member: _Declaration): ...
    def with_attr(self, member: _Declaration): ...
    def with_port(self, member: _Declaration): ...
    def with_end(self, member: _Declaration): ...
    def with_action(self, member: _Declaration): ...
    def with_state(self, member: _Declaration): ...

class _Usage(_Declaration):
    def end(self, target: Any | None = None): ...
    def with_part(self, member: _Declaration): ...
    def with_item(self, member: _Declaration): ...
    def with_attr(self, member: _Declaration): ...
    def with_port(self, member: _Declaration): ...
    def with_action(self, member: _Declaration): ...
    def with_state(self, member: _Declaration): ...
    def with_end(self, member: _Declaration): ...
    def connects(
        self,
        source: Any,
        target: Any,
        *,
        source_name: str = "source",
        target_name: str = "target",
        source_type: Any | None = None,
        target_type: Any | None = None,
    ): ...
class PartDefinition(_Definition): ...
class PartUsage(_Usage): ...
class ItemDefinition(_Definition): ...
class ItemUsage(_Usage): ...
class AttributeDefinition(_Definition): ...
class AttributeUsage(_Usage): ...
class PortDefinition(_Definition): ...
class PortUsage(_Usage): ...
class ConnectionDefinition(_Definition): ...
class ConnectionUsage(_Usage): ...
class ActionDefinition(_Definition): ...
class ActionUsage(_Usage): ...
class PerformActionUsage(_Usage): ...
class ConstraintDefinition(_Definition): ...
class ConstraintUsage(_Usage): ...
class AnalysisDefinition(_Definition): ...
class AnalysisUsage(_Usage): ...
class VerificationDefinition(_Definition): ...
class VerificationUsage(_Usage): ...
class UseCaseDefinition(_Definition): ...
class UseCaseUsage(_Usage): ...
class ViewDefinition(_Definition): ...
class ViewUsage(_Usage): ...
class ViewpointDefinition(_Definition): ...
class ViewpointUsage(_Usage): ...
class ConcernDefinition(_Definition): ...
class ConcernUsage(_Usage): ...
class StakeholderUsage(_Usage): ...
class MetadataDefinition(_Definition):
    def annotates(self, target: Any): ...
class MetadataUsage(_Usage):
    def about(self, targets: Any): ...
class OccurrenceDefinition(_Definition): ...
class OccurrenceUsage(_Usage): ...
class IndividualDefinition(_Definition): ...
class IndividualUsage(_Usage): ...
class StateDefinition(_Definition): ...
class StateUsage(_Usage): ...
class TransitionUsage(_Usage): ...
class RequirementDefinition(_Definition): ...
class InterfaceDefinition(_Definition): ...
