from .authoring import (
    ActionDefinition,
    ActionUsage,
    AnalysisDefinition,
    AnalysisUsage,
    AttributeDefinition,
    AttributeUsage,
    ConnectionDefinition,
    ConnectionUsage,
    ConstraintDefinition,
    ConstraintUsage,
    ItemDefinition,
    ItemUsage,
    PartDefinition,
    PartUsage,
    PortDefinition,
    PortUsage,
    RequirementDefinition,
    StateDefinition,
    StateUsage,
    TransitionUsage,
)

def part(name: str) -> PartUsage: ...
def part_def(name: str) -> PartDefinition: ...
def attr(name: str) -> AttributeUsage: ...
def attr_def(name: str) -> AttributeDefinition: ...
def item(name: str) -> ItemUsage: ...
def item_def(name: str) -> ItemDefinition: ...
def port(name: str) -> PortUsage: ...
def port_def(name: str) -> PortDefinition: ...
def connection(name: str) -> ConnectionUsage: ...
def connection_def(name: str) -> ConnectionDefinition: ...
def action(name: str) -> ActionUsage: ...
def action_def(name: str) -> ActionDefinition: ...
def constraint(name: str) -> ConstraintUsage: ...
def constraint_def(name: str) -> ConstraintDefinition: ...
def analysis(name: str) -> AnalysisUsage: ...
def analysis_def(name: str) -> AnalysisDefinition: ...
def requirement_def(name: str) -> RequirementDefinition: ...
def state(name: str) -> StateUsage: ...
def state_def(name: str) -> StateDefinition: ...
def transition(name: str) -> TransitionUsage: ...

__all__: list[str]
