from pathlib import Path
from typing import Any, Callable, Iterable, Mapping

JsonObject = dict[str, Any]
FrozenJsonObject = Mapping[str, Any]

class SemanticRef:
    qualified_name: str
    kind: str
    data: FrozenJsonObject
    @property
    def revision(self) -> str: ...
    @property
    def name(self) -> str: ...
    def attr(self, name: str, default: Any = None) -> Any: ...
    def attrs(self) -> JsonObject: ...
    def owner(self) -> str | None: ...
    def type_name(self) -> str | None: ...
    def specializes(self) -> list[str]: ...
    def children(self) -> list[SemanticRef]: ...
    def walk(self) -> Iterable[SemanticRef]: ...

class PartDefRef(SemanticRef):
    def subtypes(self, *, transitive: bool = True) -> list[PartDefRef]: ...

class PartUsageRef(SemanticRef): ...

class VariantBaseChangedError(RuntimeError): ...

class StaleSemanticRefError(RuntimeError): ...

class AnalysisQuery:
    def refs(
        self,
        *,
        kind: str | None = None,
        where: Callable[[SemanticRef], bool] | None = None,
    ) -> list[SemanticRef]: ...
    def part_defs(
        self,
        where: Callable[[PartDefRef], bool] | None = None,
    ) -> list[PartDefRef]: ...
    def part_usages(
        self,
        where: Callable[[PartUsageRef], bool] | None = None,
    ) -> list[PartUsageRef]: ...
    def subtypes(
        self,
        base: str | SemanticRef,
        *,
        transitive: bool = True,
    ) -> list[PartDefRef]: ...
    def containment(self, root: str | SemanticRef | None = None) -> list[SemanticRef]: ...

class CompiledModel:
    revision: str
    query: AnalysisQuery
    @property
    def raw(self) -> Any: ...
    @property
    def rows(self) -> tuple[FrozenJsonObject, ...]: ...
    def semantic_snapshot_json(self) -> str: ...
    def refs(self) -> list[SemanticRef]: ...
    def diff(self, other: Any) -> list[Any]: ...
    def to_records(self, refs: Iterable[SemanticRef] | None = None) -> list[JsonObject]: ...
    def to_frame(self, refs: Iterable[SemanticRef] | None = None) -> Any: ...
    def graph(self, relation: str = "containment") -> JsonObject: ...
    def simulation(self, name: str) -> SimulationConfiguration: ...
    def _repr_html_(self) -> str: ...
    def resolve(self, value: Any) -> SemanticRef: ...
    def part_def(self, name: str) -> PartDefRef: ...
    def part_usage(self, name: str) -> PartUsageRef: ...
    def part_defs(self) -> list[PartDefRef]: ...
    def part_usages(self) -> list[PartUsageRef]: ...
    def children_of(self, parent: SemanticRef) -> list[SemanticRef]: ...
    def walk(self) -> Iterable[SemanticRef]: ...
    def subtypes_of(
        self,
        base: SemanticRef,
        *,
        transitive: bool = True,
    ) -> list[PartDefRef]: ...

class SmallEdit:
    def rename(self, new_name: str) -> SmallEdit: ...
    def set_type(self, target: Any | None) -> SmallEdit: ...
    def set_value(self, value: Any) -> SmallEdit: ...
    def set_attribute(self, name: str, value: Any) -> SmallEdit: ...
    def add_specialization(self, target: Any) -> SmallEdit: ...
    def remove(self) -> None: ...

class ProjectSession:
    path: Path | None
    def __init__(self, builder: Any, *, path: str | Path | None = None) -> None: ...
    @classmethod
    def open(cls, path: str | Path, *, validate: bool = True) -> ProjectSession: ...
    @classmethod
    def from_files(
        cls,
        files: dict[str, str],
        *,
        validate: bool = True,
    ) -> ProjectSession: ...
    def in_package(
        self,
        name: str,
        *,
        stdlib_imports: bool = True,
    ) -> ProjectSession: ...
    def add(self, declaration: Any) -> ProjectSession: ...
    def edit(self, target: Any) -> SmallEdit: ...
    def compile(self) -> CompiledModel: ...
    def to_sysml(self) -> dict[str, str]: ...
    @property
    def source_fingerprint(self) -> str: ...
    def save(self, path: str | Path | None = None) -> None: ...
    def trade_study(self, name: str) -> TradeStudy: ...
    def simulation(self, name: str) -> SimulationConfiguration: ...

class TradeStudy:
    name: str
    base: ProjectSession
    def variant(self, name: str) -> Variant: ...

class Variant:
    name: str
    study: TradeStudy
    base_fingerprint: str | None
    def edit(self, target: Any) -> SmallEdit: ...
    def add(self, declaration: Any) -> Variant: ...
    def compile(self, *, allow_stale_base: bool = False) -> CompiledModel: ...
    def to_sysml(self) -> dict[str, str]: ...
    @property
    def source_fingerprint(self) -> str: ...
    @property
    def is_base_stale(self) -> bool: ...
    def assert_base_current(self) -> None: ...
    def simulation(self, name: str) -> SimulationConfiguration: ...

class SimulationConfiguration:
    name: str
    target: CompiledModel | ProjectSession | Variant
    subject: str | None
    settings: JsonObject
    @property
    def model_revision(self) -> str | None: ...
    @property
    def source_fingerprint(self) -> str | None: ...
    def for_subject(self, subject: Any) -> SimulationConfiguration: ...
    def configure(self, **settings: Any) -> SimulationConfiguration: ...
    def to_dict(self) -> JsonObject: ...
    def _repr_html_(self) -> str: ...
    def run(self) -> Any: ...
