from pathlib import Path
from typing import Any, Callable, Iterable, Mapping

JsonObject = dict[str, Any]
FrozenJsonObject = Mapping[str, Any]

class SemanticRef:
    qualified_name: str
    kind: str
    data: FrozenJsonObject
    @property
    def revision(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def declared_name(self) -> str: ...
    @property
    def model_layer(self) -> str: ...
    @property
    def metatype_name(self) -> str | None: ...
    @property
    def metatype_chain(self) -> list[str]: ...
    def attr(self, name: str, default: Any = None) -> Any: ...
    def get(self, name: str, default: Any = None) -> Any: ...
    def attrs(self) -> JsonObject: ...
    def owner(self) -> str | None: ...
    def type_name(self) -> str | None: ...
    def specializes(self) -> list[str]: ...
    def is_metatype(self, expected: str, *, include_subtypes: bool = True) -> bool: ...
    def children(self) -> list[SemanticRef]: ...
    def walk(self) -> Iterable[SemanticRef]: ...

class PartDefRef(SemanticRef):
    def subtypes(self, *, transitive: bool = True) -> list[PartDefRef]: ...

class PartUsageRef(SemanticRef): ...

class VariantBaseChangedError(RuntimeError): ...

class StaleSemanticRefError(RuntimeError): ...

class SemanticQuery:
    def __iter__(self) -> Iterable[SemanticRef]: ...
    def __len__(self) -> int: ...
    def refs(self) -> list[SemanticRef]: ...
    def count(self) -> int: ...
    def first(self) -> SemanticRef | None: ...
    def where(self, predicate: Callable[[SemanticRef], bool]) -> SemanticQuery: ...
    def where_kind_contains(self, text: str) -> SemanticQuery: ...
    def where_metatype(self, expected: str) -> SemanticQuery: ...
    def where_metatype_is(self, expected: str) -> SemanticQuery: ...
    def where_model_layer(self, expected: str) -> SemanticQuery: ...
    def order_by(self, field: str) -> SemanticQuery: ...
    def select(self, fields: Iterable[str]) -> list[JsonObject]: ...

class AnalysisQuery:
    def elements(self) -> SemanticQuery: ...
    def refs(
        self,
        *,
        kind: str | None = None,
        where: Callable[[SemanticRef], bool] | None = None,
    ) -> list[SemanticRef]: ...
    def where_metatype(self, expected: str) -> SemanticQuery: ...
    def where_metatype_is(self, expected: str) -> SemanticQuery: ...
    def where_model_layer(self, expected: str) -> SemanticQuery: ...
    def part_defs(
        self,
        where: Callable[[PartDefRef], bool] | None = None,
    ) -> list[PartDefRef]: ...
    def part_usages(
        self,
        where: Callable[[PartUsageRef], bool] | None = None,
    ) -> list[PartUsageRef]: ...
    def subtypes(
        self,
        base: str | SemanticRef,
        *,
        transitive: bool = True,
    ) -> list[PartDefRef]: ...
    def containment(self, root: str | SemanticRef | None = None) -> list[SemanticRef]: ...

class CellRunReport:
    cell_id: str
    kind: str
    status: str
    outputs: tuple[JsonObject, ...]
    artifacts: tuple[JsonObject, ...]
    diagnostics: tuple[JsonObject, ...]
    capability_report: JsonObject | None
    metadata: FrozenJsonObject
    session_id: str | None
    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> CellRunReport: ...
    def output(self, output_id: str) -> JsonObject: ...
    @property
    def result(self) -> Any: ...
    def to_dict(self) -> JsonObject: ...

class CompiledModel:
    revision: str
    query: AnalysisQuery
    @property
    def raw(self) -> Any: ...
    @property
    def rows(self) -> tuple[FrozenJsonObject, ...]: ...
    def semantic_snapshot_json(self) -> str: ...
    def refs(self) -> list[SemanticRef]: ...
    def diff(self, other: Any) -> list[Any]: ...
    def to_records(self, refs: Iterable[SemanticRef] | None = None) -> list[JsonObject]: ...
    def to_frame(self, refs: Iterable[SemanticRef] | None = None) -> Any: ...
    def graph(self, relation: str = "containment") -> JsonObject: ...
    def model_metadata(self) -> JsonObject: ...
    def graph_view(self, scope: str = "l2") -> JsonObject: ...
    def search(self, query: str) -> list[JsonObject]: ...
    def element_details(self, element_id: str) -> JsonObject: ...
    def l2_explorer(
        self,
        seed_id: str,
        *,
        expanded_parents: Iterable[str] | None = None,
        expanded_children: Iterable[str] | None = None,
        include_reference_edges: bool = True,
    ) -> JsonObject: ...
    def metatype_explorer(
        self,
        seed_id: str,
        *,
        expanded_parents: Iterable[str] | None = None,
        expanded_children: Iterable[str] | None = None,
    ) -> JsonObject: ...
    def render_view(self, document: Mapping[str, Any]) -> JsonObject: ...
    def run_cell(
        self,
        source: str,
        *,
        kind: str = "query",
        language: str | None = "mercurio_dsl",
        parameters: Mapping[str, Any] | None = None,
        cell_id: str | None = None,
        session_id: str | None = None,
    ) -> CellRunReport: ...
    def dsl(self, source: str) -> Any: ...
    def query_dsl(self, source: str) -> Any: ...
    def run_action_dsl(
        self,
        source: str,
        *,
        cell_id: str | None = None,
        session_id: str | None = None,
    ) -> CellRunReport: ...
    def action_dsl(self, source: str) -> Any: ...
    def preview_dsl(self, source: str) -> Any: ...
    def run_analysis_dsl(
        self,
        source: str,
        *,
        run_id: str | None = None,
        capability_id: str = "mercurio.dsl.analysis",
        subject_element_id: str | None = None,
        cell_id: str | None = None,
        session_id: str | None = None,
    ) -> CellRunReport: ...
    def analysis_dsl(
        self,
        source: str,
        *,
        run_id: str | None = None,
        capability_id: str = "mercurio.dsl.analysis",
        subject_element_id: str | None = None,
    ) -> JsonObject: ...
    def dsl_schema(self) -> JsonObject: ...
    def preview_transaction(self, request: Mapping[str, Any]) -> JsonObject: ...
    def simulation(self, name: str) -> SimulationConfiguration: ...
    def _repr_html_(self) -> str: ...
    def resolve(self, value: Any) -> SemanticRef: ...
    def part_def(self, name: str) -> PartDefRef: ...
    def part_usage(self, name: str) -> PartUsageRef: ...
    def part_defs(self) -> list[PartDefRef]: ...
    def part_usages(self) -> list[PartUsageRef]: ...
    def children_of(self, parent: SemanticRef) -> list[SemanticRef]: ...
    def walk(self) -> Iterable[SemanticRef]: ...
    def subtypes_of(
        self,
        base: SemanticRef,
        *,
        transitive: bool = True,
    ) -> list[PartDefRef]: ...

class SmallEdit:
    def rename(self, new_name: str) -> SmallEdit: ...
    def set_type(self, target: Any | None) -> SmallEdit: ...
    def set_value(self, value: Any) -> SmallEdit: ...
    def set_attribute(self, name: str, value: Any) -> SmallEdit: ...
    def add_specialization(self, target: Any) -> SmallEdit: ...
    def remove(self) -> None: ...

class TransactionBuilder:
    label: str
    def rename(self, element: Any, new_name: str) -> TransactionBuilder: ...
    def set_attribute(
        self,
        element: Any,
        attribute: str,
        value: Any,
    ) -> TransactionBuilder: ...
    def to_dict(self) -> JsonObject: ...
    def preview(self) -> JsonObject: ...
    def apply(self) -> Any: ...

class ProjectSession:
    path: Path | None
    def __init__(self, builder: Any, *, path: str | Path | None = None) -> None: ...
    @classmethod
    def open(cls, path: str | Path, *, validate: bool = True) -> ProjectSession: ...
    @classmethod
    def from_files(
        cls,
        files: dict[str, str],
        *,
        validate: bool = True,
    ) -> ProjectSession: ...
    def in_package(
        self,
        name: str,
        *,
        stdlib_imports: bool = True,
    ) -> ProjectSession: ...
    def add(self, declaration: Any) -> ProjectSession: ...
    def edit(self, target: Any) -> SmallEdit: ...
    def transaction(self, label: str) -> TransactionBuilder: ...
    def compile(self) -> CompiledModel: ...
    def to_sysml(self) -> dict[str, str]: ...
    @property
    def source_fingerprint(self) -> str: ...
    def save(self, path: str | Path | None = None) -> None: ...
    def run_cell(
        self,
        source: str,
        *,
        kind: str = "query",
        language: str | None = "mercurio_dsl",
        parameters: Mapping[str, Any] | None = None,
        cell_id: str | None = None,
        session_id: str | None = None,
    ) -> CellRunReport: ...
    def dsl(self, source: str) -> Any: ...
    def query_dsl(self, source: str) -> Any: ...
    def run_action_dsl(
        self,
        source: str,
        *,
        cell_id: str | None = None,
        session_id: str | None = None,
    ) -> CellRunReport: ...
    def action_dsl(self, source: str) -> Any: ...
    def preview_dsl(self, source: str) -> Any: ...
    def run_analysis_dsl(
        self,
        source: str,
        *,
        run_id: str | None = None,
        capability_id: str = "mercurio.dsl.analysis",
        subject_element_id: str | None = None,
        cell_id: str | None = None,
        session_id: str | None = None,
    ) -> CellRunReport: ...
    def analysis_dsl(
        self,
        source: str,
        *,
        run_id: str | None = None,
        capability_id: str = "mercurio.dsl.analysis",
        subject_element_id: str | None = None,
    ) -> JsonObject: ...
    def dsl_schema(self) -> JsonObject: ...
    def model_metadata(self) -> JsonObject: ...
    def graph_view(self, scope: str = "l2") -> JsonObject: ...
    def search(self, query: str) -> list[JsonObject]: ...
    def element_details(self, element_id: str) -> JsonObject: ...
    def l2_explorer(
        self,
        seed_id: str,
        *,
        expanded_parents: Iterable[str] | None = None,
        expanded_children: Iterable[str] | None = None,
        include_reference_edges: bool = True,
    ) -> JsonObject: ...
    def metatype_explorer(
        self,
        seed_id: str,
        *,
        expanded_parents: Iterable[str] | None = None,
        expanded_children: Iterable[str] | None = None,
    ) -> JsonObject: ...
    def render_view(self, document: Mapping[str, Any]) -> JsonObject: ...
    def trade_study(self, name: str) -> TradeStudy: ...
    def simulation(self, name: str) -> SimulationConfiguration: ...

class TradeStudy:
    name: str
    base: ProjectSession
    def variant(self, name: str) -> Variant: ...

class Variant:
    name: str
    study: TradeStudy
    base_fingerprint: str | None
    def edit(self, target: Any) -> SmallEdit: ...
    def transaction(
        self,
        label: str,
        *,
        allow_stale_base: bool = False,
    ) -> TransactionBuilder: ...
    def add(self, declaration: Any) -> Variant: ...
    def compile(self, *, allow_stale_base: bool = False) -> CompiledModel: ...
    def to_sysml(self) -> dict[str, str]: ...
    @property
    def source_fingerprint(self) -> str: ...
    @property
    def is_base_stale(self) -> bool: ...
    def assert_base_current(self) -> None: ...
    def simulation(self, name: str) -> SimulationConfiguration: ...
    def run_cell(
        self,
        source: str,
        *,
        kind: str = "query",
        language: str | None = "mercurio_dsl",
        parameters: Mapping[str, Any] | None = None,
        cell_id: str | None = None,
        session_id: str | None = None,
        allow_stale_base: bool = False,
    ) -> CellRunReport: ...
    def dsl(self, source: str, *, allow_stale_base: bool = False) -> Any: ...
    def query_dsl(self, source: str, *, allow_stale_base: bool = False) -> Any: ...
    def run_action_dsl(
        self,
        source: str,
        *,
        cell_id: str | None = None,
        session_id: str | None = None,
        allow_stale_base: bool = False,
    ) -> CellRunReport: ...
    def action_dsl(self, source: str, *, allow_stale_base: bool = False) -> Any: ...
    def preview_dsl(self, source: str, *, allow_stale_base: bool = False) -> Any: ...
    def run_analysis_dsl(
        self,
        source: str,
        *,
        run_id: str | None = None,
        capability_id: str = "mercurio.dsl.analysis",
        subject_element_id: str | None = None,
        cell_id: str | None = None,
        session_id: str | None = None,
        allow_stale_base: bool = False,
    ) -> CellRunReport: ...
    def analysis_dsl(
        self,
        source: str,
        *,
        run_id: str | None = None,
        capability_id: str = "mercurio.dsl.analysis",
        subject_element_id: str | None = None,
        allow_stale_base: bool = False,
    ) -> JsonObject: ...
    def dsl_schema(self, *, allow_stale_base: bool = False) -> JsonObject: ...
    def model_metadata(self, *, allow_stale_base: bool = False) -> JsonObject: ...
    def graph_view(self, scope: str = "l2", *, allow_stale_base: bool = False) -> JsonObject: ...
    def search(self, query: str, *, allow_stale_base: bool = False) -> list[JsonObject]: ...
    def element_details(self, element_id: str, *, allow_stale_base: bool = False) -> JsonObject: ...
    def l2_explorer(
        self,
        seed_id: str,
        *,
        expanded_parents: Iterable[str] | None = None,
        expanded_children: Iterable[str] | None = None,
        include_reference_edges: bool = True,
        allow_stale_base: bool = False,
    ) -> JsonObject: ...
    def metatype_explorer(
        self,
        seed_id: str,
        *,
        expanded_parents: Iterable[str] | None = None,
        expanded_children: Iterable[str] | None = None,
        allow_stale_base: bool = False,
    ) -> JsonObject: ...
    def render_view(
        self,
        document: Mapping[str, Any],
        *,
        allow_stale_base: bool = False,
    ) -> JsonObject: ...

class SimulationConfiguration:
    name: str
    target: CompiledModel | ProjectSession | Variant
    subject: str | None
    settings: JsonObject
    @property
    def model_revision(self) -> str | None: ...
    @property
    def source_fingerprint(self) -> str | None: ...
    def for_subject(self, subject: Any) -> SimulationConfiguration: ...
    def configure(self, **settings: Any) -> SimulationConfiguration: ...
    def to_dict(self) -> JsonObject: ...
    def _repr_html_(self) -> str: ...
    def run(self) -> Any: ...
